[[redirects]]
  from = "/blog/:title"
  to = "https://blog.madsbuch.com/:title"
  status = 301
  force = true
[[redirects]]
  from = "/blog/"
  to = "https://blog.madsbuch.com/"
  status = 301
  force = true
[[redirects]]
  from = "/thesis"
  to = "https://thesis.madsbuch.com/"
  status = 301
  force = true
